import type { TreatmentStep } from '@/view/lib/TreatmentTrail';

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * Builds a self-contained, printable HTML handoff document from the treatment
 * trail. Used by expo-print to produce the PDF. Inline CSS uses the redesign
 * palette; print-color-adjust keeps the brand colors in the exported PDF.
 */
export function buildTreatmentHandoffHtml(
  steps: TreatmentStep[],
  generatedAt: string
): string {
  const finalStep = steps[steps.length - 1];
  const recommendation = finalStep?.outcomeTitle ?? '—';

  const rows = steps
    .map((s, i) => {
      const scoreLine =
        s.score !== null
          ? `<div class="score">Score: ${s.score}</div>`
          : '';
      return `
      <div class="step">
        <div class="badge">${i + 1}</div>
        <div class="step-body">
          <div class="algo">${escapeHtml(s.algorithmTitle)}</div>
          <div class="outcome">${escapeHtml(s.outcomeTitle ?? '—')}</div>
          ${scoreLine}
        </div>
      </div>`;
    })
    .join('');

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<style>
  * { box-sizing: border-box; }
  body {
    font-family: -apple-system, "Segoe UI", Roboto, sans-serif;
    color: #0B1220; margin: 0; padding: 32px;
    -webkit-print-color-adjust: exact; print-color-adjust: exact;
  }
  .cover { border-bottom: 2px solid #1E4E8C; padding-bottom: 16px; margin-bottom: 24px; }
  .eyebrow { text-transform: uppercase; letter-spacing: .08em; font-size: 11px; font-weight: 600; color: #1E4E8C; }
  h1 { font-size: 26px; font-weight: 700; margin: 6px 0 4px; }
  .generated { font-size: 12px; color: #667085; }
  .fields { display: flex; gap: 24px; margin: 20px 0 28px; }
  .field { flex: 1; font-size: 12px; color: #475467; }
  .field .line { border-bottom: 1px solid #E4E7EB; height: 26px; margin-top: 4px; }
  .recommendation { background: #EAF0F8; border: 1px solid #1E4E8C; border-radius: 10px; padding: 14px 16px; margin-bottom: 28px; }
  .recommendation .label { font-size: 11px; text-transform: uppercase; letter-spacing: .08em; color: #1E4E8C; font-weight: 600; }
  .recommendation .value { font-size: 16px; font-weight: 600; margin-top: 4px; }
  .section-title { font-size: 13px; text-transform: uppercase; letter-spacing: .08em; color: #667085; font-weight: 600; margin-bottom: 12px; }
  .step { display: flex; gap: 12px; padding: 12px 0; border-bottom: 1px solid #EEF0F3; }
  .badge { width: 26px; height: 26px; border-radius: 999px; background: #EAF0F8; color: #1E4E8C; font-weight: 700; font-size: 12px; display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
  .algo { font-size: 14.5px; font-weight: 600; }
  .outcome { font-size: 13px; color: #475467; margin-top: 2px; }
  .score { font-size: 12px; color: #667085; margin-top: 2px; }
  .footer { margin-top: 32px; font-size: 10px; color: #667085; }
</style>
</head>
<body>
  <div class="cover">
    <div class="eyebrow">Treatment Handoff</div>
    <h1>Ischemic Stroke — Treatment Plan</h1>
    <div class="generated">Generated ${escapeHtml(generatedAt)}</div>
  </div>

  <div class="fields">
    <div class="field">Patient ID<div class="line"></div></div>
    <div class="field">Clinician<div class="line"></div></div>
    <div class="field">Signature<div class="line"></div></div>
  </div>

  <div class="recommendation">
    <div class="label">Final recommendation</div>
    <div class="value">${escapeHtml(recommendation)}</div>
  </div>

  <div class="section-title">Decision path</div>
  ${rows}

  <div class="footer">
    This document was generated by the Ischemic Stroke app for clinical handoff.
    It is a decision-support aid and does not replace clinical judgment.
  </div>
</body>
</html>`;
}
